Updated translations from Phrase
octave-online/oos-translations pull request #10
Opened 2021-01-11 09:56 UTC by oos-phrase-sync

Exported the most recent locale files from Phrase

2021-01-11 10:00 UTC, sffc commented
@Neilblaze Can you verify these 7 new strings from machine translation?

English version:
https://github.com/octave-online/oos-translations/commit/acd0cb75f8fc5cab3c2955e09becea4481e3fa2e

Thank you!

2021-01-11 13:51 UTC, Neilblaze commented on locales/bn.json
> +    "message": "দ্রষ্টব্য: এটি একটি রিড-ওনলি বালতি; আপনার সম্পাদনা অস্থায়ী। আপনার সম্পাদনা স্থায়ী করতে, বালতি নাম ক্লিক করে বালতি ফর্ক করুন:",
Change this to this :arrow_right:  `"message": "দ্রষ্টব্য: এটি একটি রিড-ওনলি বাকেট; আপনার সম্পাদনা অস্থায়ী। আপনার সম্পাদনা স্থায়ী করতে, বাকেট নাম ক্লিক করে বাকেট ফর্ক করুন:"`

2021-01-11 13:53 UTC, Neilblaze commented on locales/bn.json
> +    "message": "এই বালতি ফর্ক করুন",
Change this to this :arrow_right:  `"message": "এই বাকেটটি ফর্ক করুন"`

2021-01-11 13:54 UTC, Neilblaze commented on locales/bn.json
> +    "message": "এই বালতি বা প্রকল্পের নিজস্ব অনুলিপি তৈরি করতে নিচে ক্লিক করুন।",
Change this to this :arrow_right:  `"message": "এই বাকেটটির বা প্রকল্পের নিজস্ব অনুলিপি তৈরি করতে নিচে ক্লিক করুন।"`

2021-01-11 13:55 UTC, Neilblaze requested changes
Minor changes required :)

2021-01-12 03:28 UTC, sffc approved these changes
All done!  Thanks!

2021-01-12 03:29 UTC, merged