Adding news strings in Bengali
octave-online/oos-translations pull request #8
Opened 2021-01-05 11:27 UTC by sffc

Hi @Neilblaze,

I added some new strings in English in https://github.com/octave-online/oos-translations/commit/a350685c405a7dbcc2a23ac94e6dbfae18250ef2.  I used machine translation to generate Bengali for them.  Can you verify that the translations are ok?  Thank you!

2021-01-05 11:43 UTC, Neilblaze commented on locales/bn.json
> +    "message": "বালতি এবং প্রকল্প:",
replace via this :arrow_right: `"message": "আপনার বাকেট এবং প্রকল্প:"

2021-01-05 11:47 UTC, Neilblaze commented on locales/bn.json
> +    "message": "প্রকল্পে মধ্যে ফাইলস",
Replace via this :arrow_right: `"message": "প্রকল্পের মধ্যে ফাইলস"`

2021-01-05 11:48 UTC, Neilblaze requested changes
Two minor changes, & you're good to go! :tada: 
Never seen so perfect translation. :laughing:

2021-01-06 02:35 UTC, sffc commented
Thanks!

2021-01-06 02:35 UTC, merged